// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebGestionClientes.Models;

#nullable disable

namespace WebGestionClientes.Migrations
{
    [DbContext(typeof(DBGestionClientesContext))]
    [Migration("20240408005040_CambiosEnBase")]
    partial class CambiosEnBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebGestionClientes.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("WebGestionClientes.Models.CuentaCorriente", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoId"));

                    b.Property<int?>("ClienteId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FhMovimiento")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ImporteCredito")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ImporteDebito")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("MovimientoId")
                        .HasName("PK__CuentaCo__BF923C2C29A1D401");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("CuentaCorriente", (string)null);
                });

            modelBuilder.Entity("WebGestionClientes.Models.CuentaCorriente", b =>
                {
                    b.HasOne("WebGestionClientes.Models.Cliente", "Cliente")
                        .WithOne("CuentaCorriente")
                        .HasForeignKey("WebGestionClientes.Models.CuentaCorriente", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("WebGestionClientes.Models.Cliente", b =>
                {
                    b.Navigation("CuentaCorriente")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
